using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace S3
{
    internal class Car
    {
        #region Attributes
        private int id = default; // 4 bytes
        private string? model = default;  // 4 bytes
        private double speed = default;  // 8 bytes
        #endregion

        #region Constructor
        // Emmpty parameterless Constructor [Default Constructor]
        // Auto-Generated by Compiler

        //public Car()
        //{
            
        //}

        // user defiend constructor
        public Car(int id,string? model,double speed)
        {
            this.id = id;
            this.model = model;
            this.speed = speed;
            Console.WriteLine("1st CTOR");
        }

        public Car(int id,string? model) : this(id,model,250)
        {
            //this.id = id;
            //this.model = model;
            //this.speed = 250;
            Console.WriteLine("2nd CTOR");
        }
        public Car(int id) : this (id,"Audi")
        {
            //this.id = id;
            //this.model = "Audi";
            //this.speed = 250;
            Console.WriteLine("3rd CTOR");
        }

        #endregion

        #region Properties

        public int Id
        {
            get { return id; }
            set { id = value; }
        }

        public string Model
        {
            get { return model; } 
            set { model = value; }
        }

        public double Speed
        {
            get { return speed; }
            set { speed = value; }
        }





        #endregion

        #region Methods

        public override string ToString()
        {
            return $"Id = {id}\nModel = {model}\nSpeed = {speed}";
        }

        #endregion


    }
}
