using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace S3
{
    internal class Car
    {
        #region Attributes
        private int id = default; // 4 bytes
        private string? model = default;  // 4 bytes
        private double speed = default;  // 8 bytes
        #endregion

        #region Constructor
        // Emmpty parmterless Constructor [Default Constructor]
        // Auto-Generated by Compiler

        //public Car()
        //{
            
        //}

        // user defiend constructor
        public Car(int id,string model,double speed)
        {
            this.id = id;
            this.model = model;
            this.speed = speed;
        }

        #endregion

        #region Properties

        public int Id
        {
            get { return id; }
            set { id = value; }
        }

        public string Model
        {
            get { return model; } 
            set { model = value; }
        }

        public double Speed
        {
            get { return speed; }
            set { speed = value; }
        }





        #endregion

        #region Methods

        public override string ToString()
        {
            return $"Id = {id}\nModel = {model}\nSpeed = {speed}";
        }

        #endregion


    }
}
